Repository dimagi/Vellum, pull requests merged in 2019-08, with the labels that each got.

#959 Add vocabulary section to readme [skip ci]
  README.md
Labels: product/invisible

#958 Maintain xpath referencess on copy/paste
  src/copy-paste.js
  src/form.js
  src/itemset.js
  src/javaRosa/plugin.js
  src/modeliteration.js
  src/mugs.js
  src/richText.js
  tests/copy-paste.js
  tests/datasources.js
Labels: announce, product/all-users-all-environments

#960 Updated languages menu to scroll vertically
  src/less-style/structure.less
  src/templates/main.html
  src/window.js
Labels: product/all-users-all-environments

#961 Updated approach to scrolling languages menu
  src/less-style/structure.less
  src/templates/main.html
  src/window.js
Labels: product/all-users-all-environments

#962 Removed Remote Request question type
  src/base.js
  src/main.js
  src/remoteRequest.js
  tests/main.js
  tests/options.js
  tests/remoteRequest.js
  tests/static/remoteRequest/remoteRequest.xml
Labels: product/feature-flag

#963 Fixed app properties panel not collapsing property due to scrolling m…
  src/less-style/structure.less
Labels: passed QA, product/all-users-all-environments
