Repository dimagi/Vellum, pull requests merged in 2021-01, with the labels that each got.

#985 Fix - "Security Error" Dialogue Box in Firefox
  src/core.js
  src/widgets.js
  tests/urlHash.js
Labels: product/all-users-all-environments

#996 Bump markdown-it version
  package.json
  yarn.lock
Labels: awaiting QA, dependencies, product/invisible

#997 Upgrade less
  .travis.yml
  Makefile
  README.md
  package.json
  src/main.js
  src/widgets.js
  start-server.sh
  test
  tests/urlHash.js
  yarn.lock
Labels: product/invisible
